### ISSUE TITLE
Stable version for installing via composer?

### ISSUE THREAD

**Issue by Stretch96** [PhilETaylor/teller-api#1]
It appears there isn't yet a stable version:

```
Could not find package philetaylor/teller-api at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

Only `dev-master` is currently available, so need to install by adding:

```
{
    "require": {
        "philetaylor/teller-api": "@dev"
    }
}
```

then running `composer update`.

Is there a reason behind not yet having a stable version?

**Comment by PhilETaylor** [comment]
There is no current stable version. This was a quick sunday afternoon project thats still incomplete - yet working.

**Comment by Stretch96** [comment]
Okie dokie ... So far so good 👍

**Comment by PhilETaylor** [comment]
Looks like Teller.io have shut down most of the service this API was calling :-( They have gone in a different direction :(

**Comment by Stretch96** [comment]
Yup I was just going through cleaning my open issues 😬
